export type { Hunk, FilePatch, Outcome, TestResult } from "./types.js";
export { snapshotWorkingTree, pruneSnapshots } from "./git/snapshot.js";
export { createSandbox, DEFAULT_LINKED_PATHS } from "./git/worktree.js";
export type { Sandbox, SandboxOptions } from "./git/worktree.js";
export { runTest, DEFAULT_TEST_TIMEOUT_MS } from "./runner/test.js";
export { repoRoot, resolveRef, isDirty, hasCommits } from "./git/repo.js";
export { checkPreconditions } from "./commands/doctor.js";
export { listHunks, formatHunkListing } from "./commands/hunks.js";
export type { HunkListing } from "./commands/hunks.js";
export { parseDiff, collectHunks } from "./diff/parse.js";
export { buildPatch, applySubset, resetSandbox } from "./diff/apply.js";
export { diffCommits, applyPatch, resetWorktree, DEFAULT_CONTEXT_LINES } from "./git/diff.js";
export type { PreconditionReport } from "./commands/doctor.js";
export { search, DEFAULT_MAX_PROBES } from "./commands/search.js";
export type { SearchReport } from "./commands/search.js";
export { ddmin } from "./search/ddmin.js";
export type { Probe, ProbeEvent, SearchResult } from "./search/ddmin.js";
export { formatCulprit } from "./report/format.js";
